# Generated by Django 4.2.2 on 2024-03-21 02:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('details', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images')),
                ('links', models.URLField()),
            ],
        ),
    ]
